spring:
  application:
    name: gestion-ecole-backend
  
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true  # Gain 30-50% sur le démarrage
  
  datasource:
    url: jdbc:postgresql://shortline.proxy.rlwy.net:33602/railway
    username: postgres
    password: qnvwvvSydkEszgeSiMEqWswVfaMcBnKD
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # ATTENTION: Supprime et recrée les tables à chaque démarrage!
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.domain.com
        auth: true
    host: smtp.domain.com
    username: test@asystresources.com
    password: Asyst@2024
    port: 587
  
  # Désactiver le cache pour le développement
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  cache:
    type: simple
    cache-names:
      - users
      - classes
      - eleves
      - factures

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration: 3600000 # 1 hour in milliseconds
    refresh-expiration: 2592000000 # 30 days in milliseconds
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: "*"
    allow-credentials: true

# Application Configuration
app:
  file:
    upload-dir: ${FILE_UPLOAD_DIR:uploads}
    max-size: 10485760 # 10MB
    allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx
  
  pagination:
    default-page-size: 20
    max-page-size: 100
  
  notification:
    email:
      from: ${NOTIFICATION_EMAIL_FROM:noreply@ecole.com}
      enabled: ${NOTIFICATION_EMAIL_ENABLED:true}
    sms:
      enabled: ${NOTIFICATION_SMS_ENABLED:false}
      provider: ${SMS_PROVIDER:twilio}
  
  payment:
    mobile-money:
      enabled: true
      providers:
        - orange-money
        - mtn-momo
        - airtel-money
    card:
      enabled: false
      provider: stripe

# Logging Configuration (Optimisé pour démarrage rapide)
logging:
  level:
    root: WARN                          # Gain 5-10% sur démarrage
    com.gescom.ecole: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN             # DEBUG ralentit beaucoup
    org.hibernate.type.descriptor.sql.BasicBinder: WARN  # TRACE = très lent
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gestion-ecole.log
    max-size: 10MB
    max-history: 30

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false
